# Generated by Django 4.1.3 on 2023-10-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
